database:
  uri: sqlite:////tmp/db.sqlite3
rq:
  host: localhost
  port: 6379
workers:  # Define them here, and use the same key in workers' configs.
  internal01:
    key: CorrectStapleBatteryHorse
  america02:
    key: admin123
telegram:
  token: 0:invalidtoken
