database:
  uri: sqlite:////tmp/db.sqlite3
rq:
  host: localhost
  port: 6379
workers:  # Define them here, and use the same key in workers' configs.
  internal01:
    key: CorrectStapleBatteryHorse
  america02:
    key: admin123
telegram:
  token: 0:invalidtoken
postmark:
  server_token: put-your-token-here
  from_address: verified@sender.signature.example
  template_id: 1200342
  up_text: Up
  down_text: Down
cachet:
  api_endpoint: http://127.0.0.1/api/
  api_token: t896DlatyWtst4LgKdlo
